branches:
  only:
  - main
cache: bundler
language: ruby
rvm:
  - 2.7.2
  - 3.1.3 
  - 3.2.1

script:
- bundle exec rspec

jobs:
  include:
    - stage: gem release
      rvm: 3.2.1
      if: type != pull_request
      script: skip
      deploy:
        provider: script
        script: ./bin/travis_deploy.sh
        on:
          branch: main
