branches:
  only:
  - main
cache: bundler
language: ruby
rvm:
  - 2.7.2
  - 3.1.3 
  - 3.2.1

script:
- bundle exec rspec

deploy:
  provider: script
  script: ./bin/travis_deploy
  on:
    branch: main
    condition: type != pull_request
